spring:
  cloud:
    config:
      server:
        native:
          search-locations:
            - classpath:/config
            - classpath:/config/{application}
            - classpath:/config/{application}/profile

management:
  servet:
    base-path: /
    port: 0