spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sinanKarabulut/config-server.git
          username: sinankarabulut87@gmail.com
          password: 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
          search-paths:
            - src/main/resources/config
            - src/main/resources/config/{application}
          clone-on-start: true
          default-label: master
          skip-ssl-validation: true

